### ISSUE TITLE
PyGanja not working in VSCode Jupyter

### ISSUE THREAD

**Issue by RobinKa** [pygae/pyganja#46]
VSCode can directly open jupyter notebooks (https://code.visualstudio.com/docs/python/jupyter-support). However PyGanja's draw doesn't show up in them.

![image](https://user-images.githubusercontent.com/2614101/85873311-d8fca680-b7c8-11ea-98d1-9092ac801f23.png)

**Comment by eric-wieser** [comment]
Possibly related: https://github.com/microsoft/vscode-python/issues/3429

When I try to use the notebook feature my VSCode just becomes a dead shell around a jupyter notebook, and then I have to terminate vscode in order to open any other file.

**Comment by eric-wieser** [comment]
It's something to do with these lines:

https://github.com/microsoft/vscode-python/blob/6abd30e50a36283b97f25418c357738021d2e9c8/src/datascience-ui/interactive-common/transforms.tsx#L92-L95

I can't work out where the code they reference lives, but VSCode is doing something unexpected with our `IPython.display.Javascript` output.

You can attach an inspector via the `Developer: Open Webview Developer Tools` command in VS Code. It fails with an error like:
```
Failed to load resource: net::ERR_FAILED
require.js:143 Uncaught Error: Script error for "Algebra"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)
```

It seems that our `require("Algebra")` is doing something weird, and not finding the local definition.

**Comment by eric-wieser** [comment]
Alright, so what's happening is

* Our code is being eval'd here: https://github.com/nteract/nteract/blob/v0.12.3/packages/transforms/src/javascript.js#L8-L25
* `ganja.js` is detecting a `module.exports`, which is defined as:
  ![image](https://user-images.githubusercontent.com/425260/86180883-e7c6be80-bb24-11ea-9120-a59da2a40a5b.png)
  It uses this instead of the normal requireJS `define`. This means it replaces the `@nteract/transforms` package with itself!
* `pyganja` uses `requirejs`, which does not know about module exports, and so blows up on a URL fetch of `Algebra.js`.

We can fix this either by:
1. Getting `nteract` to clear `module` before calling eval. No good can come of letting eval'd code have access to it.
2. Having `ganja.js` specifically ignore `module.exports` if it is already populated, and fall back on `define`.
3. Set `var module = null` in pyganja.

Since I'm a bit suspicious that the upstream code no longer exists, I think we have to pick option 2 or 3. @enkimute, do you have a preference?

**Comment by eric-wieser** [comment]
Just to prove option 3 works:

![image](https://user-images.githubusercontent.com/425260/86181604-42144f00-bb26-11ea-87a4-7eaf328c66ab.png)

**Comment by eric-wieser** [comment]
Concluded that option 3 was the right way to go, because really we want to force ganja.js to operate in `requirejs` mode
